import type { Trip, TripPass } from '../state/store';
import { recordsLawFor, type RecordsLaw } from './recordsLaw';

const CSV_HEADER = [
  'time_iso',
  'time_local',
  'lat',
  'lon',
  'manufacturer',
  'operator',
  'state',
  'camera_direction_deg',
  'osm_url',
  'distance_from_road_m',
  'possibly_not_visible',
  'facing_away',
  'metres_into_drive',
];

function osmUrl(p: TripPass): string {
  return `https://www.openstreetmap.org/${p.osmType}/${p.cameraId}`;
}

function csvField(v: string | number | boolean | undefined): string {
  if (v === undefined) return '';
  const s = String(v);
  return /[",\r\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

/** CSV of every camera passed on the trip, one row per pass, CRLF line endings. */
export function buildTripCsv(trip: Trip): string {
  const rows = trip.passes.map((p) =>
    [
      p.at,
      new Date(p.at).toLocaleString(),
      p.lngLat[1].toFixed(6),
      p.lngLat[0].toFixed(6),
      p.manufacturer,
      p.operator,
      p.state,
      p.direction,
      osmUrl(p),
      p.distanceM,
      p.possiblyNotVisible,
      p.facingAway ?? false,
      Math.round(p.alongM),
    ]
      .map(csvField)
      .join(','),
  );
  return [CSV_HEADER.join(','), ...rows].join('\r\n') + '\r\n';
}

/** Operator label for a pass; untagged operators are grouped by manufacturer. */
export function passOperator(p: TripPass): string {
  const op = p.operator?.trim();
  if (op) return op;
  return `Operator not tagged (manufacturer: ${p.manufacturer ?? 'unknown'})`;
}

export interface OperatorGroup {
  operator: string;
  /** true when the OSM operator tag was present (MuckRock lookup makes sense) */
  tagged: boolean;
  passes: TripPass[];
  /** Statute for the state of the first pass with a resolved state, if any. */
  law: RecordsLaw | null;
  /** Passes span more than one state; the citation above covers only the first. */
  mixedStates: boolean;
}

/** Passes grouped per operator in order of first pass. */
export function groupByOperator(trip: Trip): OperatorGroup[] {
  const groups = new Map<string, OperatorGroup>();
  for (const p of trip.passes) {
    const k = passOperator(p);
    const g = groups.get(k);
    if (g) g.passes.push(p);
    else groups.set(k, { operator: k, tagged: Boolean(p.operator?.trim()), passes: [p], law: null, mixedStates: false });
  }
  for (const g of groups.values()) {
    const states = new Set(g.passes.map((p) => recordsLawFor(p.state)?.code).filter(Boolean));
    g.law = recordsLawFor(g.passes.find((p) => recordsLawFor(p.state))?.state);
    g.mixedStates = states.size > 1;
  }
  return [...groups.values()];
}

function header(trip: Trip): string[] {
  const start = new Date(trip.startedAt);
  const end = new Date(trip.endedAt);
  const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
  const lines = [
    'Records request — vehicle passing automated license plate readers',
    `${trip.mode === 'watch' ? 'Scout session' : 'Trip'}: ${trip.originLabel || 'Start'} → ${trip.destinationLabel || 'End'}`,
    `Date: ${start.toLocaleDateString()}, ${start.toLocaleTimeString()} – ${end.toLocaleTimeString()} (${tz})`,
  ];
  if (trip.mode === 'simulate') lines.push('NOTE: this was a simulated drive generated by the Elude app, not a real trip.');
  return lines;
}

function requestBody(law: RecordsLaw | null, mixedStates: boolean): string[] {
  const under = law
    ? `under the ${law.law} (${law.citation})${mixedStates ? ' and the corresponding law of any other state listed' : ''}`
    : 'under the applicable public-records / data-access law';
  const lines = [
    '',
    `I am requesting all records associated with my vehicle captured by the automated license plate reader (ALPR) cameras listed below during the times shown, including images, plate reads, timestamps, location data, and any hot-list matches or sharing/retention records, ${under}. Please contact me if any fee or identification is required.`,
  ];
  if (law) lines.push(`The statute provides for a response within ${law.deadline}.`);
  return lines;
}

function passLine(p: TripPass): string {
  return `- ${new Date(p.at).toLocaleString()}  ${p.lngLat[1].toFixed(6)}, ${p.lngLat[0].toFixed(6)}  ${p.manufacturer ?? 'unknown manufacturer'}  ${
    p.direction !== undefined ? `facing ${p.direction}°` : 'facing unknown'
  }  ${osmUrl(p)}${p.possiblyNotVisible ? '  (on a bridge/tunnel — may not have captured)' : ''}${p.facingAway ? '  (camera facing away — may not have captured)' : ''}`;
}

/** Plain-text request addressed to a single operator, citing that state's law. */
export function buildOperatorRequestText(trip: Trip, g: OperatorGroup): string {
  const lines = [...header(trip), `To: ${g.operator}`, ...requestBody(g.law, g.mixedStates), ''];
  for (const p of g.passes) lines.push(passLine(p));
  return lines.join('\n') + '\n';
}

/** Plain-text public-records request, passes grouped per operator in order of first pass. */
export function buildTripRequestText(trip: Trip): string {
  const groups = groupByOperator(trip);
  const laws = new Map(groups.filter((g) => g.law).map((g) => [g.law!.code, g.law!]));
  const lines = [...header(trip), ...requestBody(laws.size === 1 ? [...laws.values()][0]! : null, laws.size > 1)];
  for (const g of groups) {
    lines.push('', `== ${g.operator} ==`);
    if (g.law && laws.size > 1) lines.push(`(${g.law.law}, ${g.law.citation}; response within ${g.law.deadline})`);
    for (const p of g.passes) lines.push(passLine(p));
  }
  return lines.join('\n') + '\n';
}

export function tripFilename(trip: Trip): string {
  return `elude-trip-${trip.startedAt.slice(0, 16).replace(/[:T]/g, '-')}.csv`;
}
