import type { Trip, TripPass } from '../state/store';

const CSV_HEADER = [
  'time_iso',
  'time_local',
  'lat',
  'lon',
  'manufacturer',
  'operator',
  'camera_direction_deg',
  'osm_url',
  'distance_from_road_m',
  'possibly_not_visible',
  'facing_away',
  'metres_into_drive',
];

function osmUrl(p: TripPass): string {
  return `https://www.openstreetmap.org/${p.osmType}/${p.cameraId}`;
}

function csvField(v: string | number | boolean | undefined): string {
  if (v === undefined) return '';
  const s = String(v);
  return /[",\r\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

/** CSV of every camera passed on the trip, one row per pass, CRLF line endings. */
export function buildTripCsv(trip: Trip): string {
  const rows = trip.passes.map((p) =>
    [
      p.at,
      new Date(p.at).toLocaleString(),
      p.lngLat[1].toFixed(6),
      p.lngLat[0].toFixed(6),
      p.manufacturer,
      p.operator,
      p.direction,
      osmUrl(p),
      p.distanceM,
      p.possiblyNotVisible,
      p.facingAway ?? false,
      Math.round(p.alongM),
    ]
      .map(csvField)
      .join(','),
  );
  return [CSV_HEADER.join(','), ...rows].join('\r\n') + '\r\n';
}

function groupKey(p: TripPass): string {
  const op = p.operator?.trim();
  if (op) return op;
  return `Operator not tagged (manufacturer: ${p.manufacturer ?? 'unknown'})`;
}

/** Plain-text public-records request, passes grouped per operator in order of first pass. */
export function buildTripRequestText(trip: Trip): string {
  const start = new Date(trip.startedAt);
  const end = new Date(trip.endedAt);
  const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
  const groups = new Map<string, TripPass[]>();
  for (const p of trip.passes) {
    const k = groupKey(p);
    const g = groups.get(k);
    if (g) g.push(p);
    else groups.set(k, [p]);
  }
  const lines = [
    'Records request — vehicle passing automated license plate readers',
    `${trip.mode === 'watch' ? 'Scout session' : 'Trip'}: ${trip.originLabel || 'Start'} → ${trip.destinationLabel || 'End'}`,
    `Date: ${start.toLocaleDateString()}, ${start.toLocaleTimeString()} – ${end.toLocaleTimeString()} (${tz})`,
  ];
  if (trip.mode === 'simulate') lines.push('NOTE: this was a simulated drive generated by the Elude app, not a real trip.');
  lines.push(
    '',
    'I am requesting all records associated with my vehicle captured by the automated license plate reader (ALPR) cameras listed below during the times shown, including images, plate reads, timestamps, location data, and any hot-list matches or sharing/retention records, under the applicable public-records / data-access law. Please contact me if any fee or identification is required.',
  );
  for (const [op, passes] of groups) {
    lines.push('', `== ${op} ==`);
    for (const p of passes) {
      lines.push(
        `- ${new Date(p.at).toLocaleString()}  ${p.lngLat[1].toFixed(6)}, ${p.lngLat[0].toFixed(6)}  ${p.manufacturer ?? 'unknown manufacturer'}  ${
          p.direction !== undefined ? `facing ${p.direction}°` : 'facing unknown'
        }  ${osmUrl(p)}${p.possiblyNotVisible ? '  (on a bridge/tunnel — may not have captured)' : ''}${p.facingAway ? '  (camera facing away — may not have captured)' : ''}`,
      );
    }
  }
  return lines.join('\n') + '\n';
}

export function tripFilename(trip: Trip): string {
  return `elude-trip-${trip.startedAt.slice(0, 16).replace(/[:T]/g, '-')}.csv`;
}
